from collections.abc import Iterator, Sequence
from dataclasses import dataclass
from string.templatelib import Template
from typing import Any

from tree_sitter import Language, Node, Query, Tree

class TemplateError(Exception): ...
class TemplateSyntaxError(TemplateError): ...
class TemplateCompileError(TemplateError): ...

class Hole:
    is_variadic: bool

@dataclass(frozen=True)
class Capture(Hole):
    name: str
    kind: str | None = ...
    pattern: str | None = ...
    one_of: tuple[str, ...] | None = ...
    quantifier: str | None = ...
    @property
    def is_variadic(self) -> bool: ...

@dataclass(frozen=True)
class Wildcard(Hole):
    kind: str | None = ...

@dataclass(frozen=True)
class AnyChildren(Hole): ...

@dataclass(frozen=True)
class Alternatives(Hole):
    texts: tuple[str, ...]
    name: str | None = ...

def capture(
    name: str,
    kind: str | None = ...,
    *,
    pattern: str | None = ...,
    one_of: Sequence[str] | None = ...,
    quantifier: str | None = ...,
) -> Capture: ...
def anything(kind: str | None = ...) -> Wildcard: ...

class Match:
    @property
    def pattern_index(self) -> int: ...
    @property
    def captures(self) -> dict[str, list[Node]]: ...
    def __getitem__(self, name: str) -> Node: ...
    def __contains__(self, name: str) -> bool: ...
    def __iter__(self) -> Iterator[str]: ...
    def get(self, name: str, default: Any = ...) -> Node | Any: ...
    def all(self, name: str) -> list[Node]: ...
    def text(self, name: str, encoding: str = ...) -> str: ...

class TemplateQuery:
    def __init__(self, language: Language, template: Template) -> None: ...
    @property
    def language(self) -> Language: ...
    @property
    def sexp(self) -> str: ...
    @property
    def rendered_template(self) -> str: ...
    @property
    def capture_names(self) -> list[str]: ...
    @property
    def query(self) -> Query: ...
    def matches(self, source: str | bytes | Tree) -> list[Match]: ...
    def captures(self, source: str | bytes | Tree) -> dict[str, list[Node]]: ...
    def first(self, source: str | bytes | Tree) -> Match | None: ...

def query(language: Language, template: Template) -> TemplateQuery: ...
